---
id: living_room_p4_kobenhavn
alias: 'Sonos: Living Room Play P4 København'
description: ''
trigger: []
condition: []
action:
- service: media_player.volume_set
  data:
    volume_level: 0.2
  target:
    entity_id: media_player.living_room
- service: media_player.select_source
  data:
    source: DR P4 København
  target:
    entity_id: media_player.living_room
- service: media_player.media_play
  target:
    entity_id: media_player.living_room
mode: single
