alias: Toggle toilet lights
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.toilet_sensor_occupancy
    id: turn-on
    to: 'on'
  - platform: state
    entity_id: binary_sensor.toilet_sensor_occupancy
    id: turn-off
    to: 'off'
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: turn-on
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.night
                    state: 'off'
                sequence:
                  - service: light.turn_on
                    data:
                      brightness: 255
                    target:
                      entity_id: light.toilet_bulbs
              - conditions:
                  - condition: state
                    entity_id: binary_sensor.night
                    state: 'on'
                sequence:
                  - service: light.turn_on
                    data:
                      brightness: 1
                    target:
                      entity_id: light.toilet_bulbs
            default: []
      - conditions:
          - condition: trigger
            id: turn-off
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.toilet_bulbs
            data: {}
    default: []
mode: single
