- id: '1643822863833'
  alias: Emmas remote
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.emma_remote_brightness
    id: brightness
  - platform: state
    entity_id: sensor.emma_remote_action
    id: 'on'
    to: 'on'
  - platform: state
    entity_id: sensor.emma_remote_action
    id: 'off'
    to: 'off'
  - platform: state
    entity_id: sensor.emma_remote_action
    id: left-click
    to: arrow_left_click
  - platform: state
    entity_id: sensor.emma_remote_action
    id: right-click
    to: arrow_right_click
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: 'on'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.emmas_strip
        data: {}
    - conditions:
      - condition: trigger
        id: 'off'
      sequence:
      - service: light.turn_off
        target:
          entity_id: light.emmas_strip
        data: {}
    - conditions:
      - condition: trigger
        id: left-click
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.emmas_strip
        data:
          hs_color:
          - "{% if state_attr(var_light, \"hs_color\")[0] - 18 < 0 %}\n  {{ 360 -
            state_attr(var_light, \"hs_color\")[0] - 18 }}\n{% else %}\n  {{ state_attr(var_light,
            \"hs_color\")[0] - 18 }}\n{% endif %}"
          - '{{ state_attr(var_light, "hs_color")[1] }}'
          transition: 0.5
      - delay:
          milliseconds: 500
    - conditions:
      - condition: trigger
        id: right-click
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.emmas_strip
        data:
          hs_color:
          - "{% if state_attr(var_light, \"hs_color\")[0] + 18 > 360 %}\n  {{ state_attr(var_light,
            \"hs_color\")[0] + 18 - 360 }}\n{% else %}\n  {{ state_attr(var_light,
            \"hs_color\")[0] + 18 }}\n{% endif %}"
          - '{{ state_attr(var_light, "hs_color")[1] }}'
          transition: 0.5
    default: []
  mode: single
  variables:
    var_light: light.emmas_strip
- id: '1653921061156'
  alias: Update notifications
  description: ''
  use_blueprint:
    path: mdegat01/update_notifications.yaml
    input:
      reminder_hours: '3'
      update_entities:
      - update.home_assistant_core_update
      - update.home_assistant_operating_system_update
      - update.home_assistant_supervisor_update
      - update.studio_code_server_update
      - update.adguard_home_update
      - update.duck_dns_update
      - update.mosquitto_broker_update
      - update.zigbee2mqtt_update
      - update.wireguard_update
      - update.terminal_ssh_update
      - update.samba_share_update
      - update.home_assistant_google_drive_backup_update
      - update.influxdb_update
      mobile_app_device: 49007877174341f3f8961213599c583f
- id: '1655043793601'
  alias: Astrids lights
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 957414c082d6a974ad5157d047420dfb
    type: action
    subtype: toggle
    discovery_id: 0xbc33acfffe83dc24 action_toggle
    id: toggle
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.astrid_s_lights
  mode: single
- id: '1656424147667'
  alias: Set Washing Machine States
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.shelly_shplg_s_f1487f_current_consumption
    id: 'off'
    for:
      hours: 0
      minutes: 1
      seconds: 0
    below: '1'
  - platform: numeric_state
    entity_id: sensor.shelly_shplg_s_f1487f_current_consumption
    id: running
    above: '1'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: 'off'
      sequence:
      - service: input_select.select_option
        data:
          option: 'Off'
        target:
          entity_id: input_select.washing_machine_status
    - conditions:
      - condition: trigger
        id: 'off'
      - condition: state
        entity_id: input_select.washing_machine_status
        state: Running
      sequence:
      - service: input_select.select_option
        data:
          option: Finished
        target:
          entity_id: input_select.washing_machine_status
    - conditions:
      - condition: trigger
        id: running
      sequence:
      - service: input_select.select_option
        data:
          option: Running
        target:
          entity_id: input_select.washing_machine_status
    default: []
  mode: single
- id: '1656424427614'
  alias: Notify - Washing machine finished
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.washing_machine_status
    to: 'Off'
    from: Running
  condition: []
  action:
  - service: notify.mobile_app_klgn_phone
    data:
      message: Washing machine is done
      data:
        persisent: true
        tag: washing
        actions:
        - action: MACHINE_EMPTIED
          title: It's done
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.washing_machine_emptied
  mode: single
- id: '1656424680283'
  alias: Notify - Washing machine emptied action
  description: ''
  trigger:
  - platform: event
    event_type: mobile_app_notification
    event_data:
      action: MACHINE_EMPTIED
  condition: []
  action:
  - service: notify.mobile_app_klgn_phone
    data:
      message: clear_notification
      data:
        tag: washing
  - service: input_boolean.turn_off
    data: {}
  mode: single
- id: '1657113186860'
  alias: Notify When general waste is collected
  description: ''
  use_blueprint:
    path: klgn/renoweb_waste_blueprint.yaml
    input:
      waste: sensor.renoweb_240_l_rest_mad_14_dag
      mobile_app_device: 49007877174341f3f8961213599c583f
- id: '1659546576401'
  alias: Update previous hour price
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '59'
  condition: []
  action:
  - service: input_number.set_value
    data:
      value: '{% set _price_obj = state_attr(''sensor.energy_price'', ''today'') |
        selectattr(''hour_only'', ''=='', now().timestamp() | timestamp_custom("%H"))
        | list %} {{ _price_obj[0][''price''] }}

        '
    target:
      entity_id: input_number.previous_hour_price
  mode: single
- id: '1659547210990'
  alias: Update Hourly Electricity price
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '0'
    seconds: '30'
  condition: []
  action:
  - service: input_number.set_value
    data:
      value: '{{ state_attr(''sensor.hourly_power_usage'', ''last_period'') | float
        * states.input_number.previous_hour_price.state | float }}

        '
    target:
      entity_id: input_number.hourly_energy_price
  mode: single
- id: '1663350945169'
  alias: Toggle Sonos from Alarm State
  description: ''
  trigger:
  - platform: state
    entity_id:
    - alarm_control_panel.verisure_alarm
    id: away
    to: armed_away
  - platform: state
    entity_id:
    - alarm_control_panel.verisure_alarm
    id: home
    to: disarmed
    from: armed_away
  - platform: state
    entity_id:
    - alarm_control_panel.verisure_alarm
    id: arm-home
    to: armed_home
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: away
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id:
          - switch.office_sonos_switch
          - switch.shelly_shplg_s_f1a39a
    - conditions:
      - condition: trigger
        id: home
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id:
          - switch.office_sonos_switch
          - switch.shelly_shplg_s_f1a39a
    - conditions:
      - condition: trigger
        id: arm-home
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id:
          - switch.office_sonos_switch
          - switch.shelly_shplg_s_f1a39a
  mode: single
- id: '1663351083369'
  alias: Turn off Living Sonos Bulp when switch is turned on
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.shelly_shplg_s_f1a39a
    to: 'on'
    id: turn-on
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: turn-on
      sequence:
      - delay:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.living_room_sonos_bulp
  mode: single
- id: '1664647979067'
  alias: Living Room morning schedule
  description: ''
  trigger:
  - platform: time
    at: input_datetime.living_room_light_morning_schedule_start
    id: morning-start
  - platform: time
    at: input_datetime.living_room_light_morning_schedule_end
    id: morning-end
  - platform: numeric_state
    entity_id: sensor.sun_elevation
    id: sun-up
    above: '1'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.vacation
      state: 'off'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: morning-start
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.living_room_control_unit
        data: {}
      - service: light.turn_on
        target:
          entity_id: light.living_room_sonos_bulp
        data: {}
    - conditions:
      - condition: trigger
        id: morning-end
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.living_room_control_unit
        data: {}
      - service: light.turn_off
        target:
          entity_id: light.living_room_sonos_bulp
        data: {}
    - conditions:
      - condition: trigger
        id: sun-up
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.living_room_control_unit
        data: {}
      - service: light.turn_off
        target:
          entity_id: light.living_room_sonos_bulp
        data: {}
    default: []
  mode: single
- id: sonos_living_room_morning_schedule
  alias: 'Sonos: Living Room morning schedule '
  description: ''
  trigger:
  - platform: time
    at: input_datetime.living_room_sonos_morning_start
    id: morning-start
  - platform: time
    at: input_datetime.living_room_sonos_morning_end
    id: morning-end
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: input_boolean.vacation
      state: 'off'
  action:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: trigger
          id: morning-start
        - condition: state
          entity_id: device_tracker.klgn_phone
          state: home
      sequence:
      - service: automation.trigger
        target:
          entity_id: automation.living_room_p4_kobenhavn
        data: {}
    - conditions:
      - condition: trigger
        id: morning-end
      sequence:
      - service: media_player.media_stop
        target:
          entity_id: media_player.living_room
        data: {}
    default: []
  mode: single
