---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
    name: Mågevej
    packages: !include_dir_named integrations
    customize: !include_dir_merge_named customizations/entities
    latitude: !secret hass_latitude
    longitude: !secret hass_longitude
    elevation: !secret hass_elevation
    unit_system: metric
    temperature_unit: C
    time_zone: Europe/Copenhagen
    currency: DKK

scene: !include scenes.yaml
