---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
    name: Mågevej
    packages: !include_dir_named integrations 
    latitude: !secret hass_latitude
    longitude: !secret hass_longitude
    elevation: !secret hass_elevation
    unit_system: metric
    temperature_unit: C
    time_zone: Europe/Copenhagen
    currency: DKK

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
