---
id: kids_internet_schedule
alias: Kids' Internet Schedule
description: ''
trigger:
- platform: time
  at: 07:00:00
  id: morning-curfew
- platform: time
  at: '21:30:00'
  id: evening-curfew
condition: []
action:
- choose:
  - conditions:
    - condition: trigger
      id: morning-curfew
    sequence:
    - service: switch.turn_on
      target:
        entity_id:
        - switch.emmas_laptop
        - switch.laurits_laptop
        - switch.astrids_laptop
  - conditions:
    - condition: trigger
      id: evening-curfew
    sequence:
    - service: switch.turn_off
      target:
        entity_id:
        - switch.emmas_laptop
        - switch.laurits_laptop
        - switch.astrids_laptop
  default: []
mode: single
