---
id: sonos_stop_kids_players
alias: 'Sonos: Stop Kids'' players at night'
description: ''
trigger:
- platform: time
  at: input_datetime.kids_sonos_players_stop
condition: []
action:
- service: media_player.media_stop
  target:
    entity_id:
    - media_player.laurits_sonos
    - media_player.astrids_sonos
    - media_player.emmas_vaerelse
mode: single
