---
id: "zigbee2mqtt_create_notification_on_successfull_interview"
alias: Zigbee Device Joined Notification
trigger:
  platform: mqtt
  topic: 'zigbee2mqtt/bridge/log'
condition:
  condition: template
  value_template: '{{trigger.payload_json.type == "pairing" and trigger.payload_json.message == "interview_successful"}}'
action:
  - service: persistent_notification.create
    data_template:
      title: Device joined the zigbee2mqtt network
      message: "Name: {{trigger.payload_json.meta.friendly_name}},
                Vendor: {{trigger.payload_json.meta.vendor}},
                Description: {{trigger.payload_json.meta.description}}"
