---
id: turn_off_charging_unit
alias: Turn off charging unit at night
description: ''
trigger:
- platform: time
  at: input_datetime.hall_charger_end_time
condition: []
action:
- type: turn_off
  device_id: 9ba1e1178dd56b582d4de26be35124f3
  entity_id: switch.charge_unit_l1
  domain: switch
- type: turn_off
  device_id: 9ba1e1178dd56b582d4de26be35124f3
  entity_id: switch.charge_unit_l2
  domain: switch
- type: turn_off
  device_id: 9ba1e1178dd56b582d4de26be35124f3
  entity_id: switch.charge_unit_l3
  domain: switch
mode: single
