---
id: telegram_start_astrid_alarm
alias: 'Telegram: Start Astrid Alarm'
description: ''
trigger:
- platform: event
  event_type: telegram_command
  event_data:
    command: /upAstrid
condition: []
action:
- service: automation.trigger
  target:
    entity_id: automation.sonos_start_astrid_alarm
mode: single
