---
id: office_control_unit_toggle
alias: 'Control Unit office toggle '
description: ''
trigger:
- platform: state
  entity_id: sensor.office_dimmer_action
  id: Turn-on
  to: brightness_move_up
- platform: state
  entity_id: sensor.office_dimmer_action
  id: Turn-off
  to: brightness_move_down
condition: []
action:
- choose:
  - conditions:
    - condition: trigger
      id: Turn-on
    sequence:
    - service: switch.turn_on
      target:
        entity_id: switch.office_control_unit
  - conditions:
    - condition: trigger
      id: Turn-off
    sequence:
    - service: switch.turn_off
      target:
        entity_id: switch.office_control_unit
  default: []
mode: single
