---
id: sonos_living_room_morning_schedule
alias: "Sonos: Living Room morning schedule "
description: ""
trigger:
  - platform: time
    at: input_datetime.living_room_sonos_morning_start
    id: morning-start
  - platform: time
    at: input_datetime.living_room_sonos_morning_end
    id: morning-end
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
      - condition: state
        entity_id: input_boolean.vacation
        state: "off"
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id: morning-start
              - condition: state
                entity_id: device_tracker.oneplus_9_pro
                state: home
        sequence:
          - service: automation.trigger
            target:
              entity_id: automation.living_room_p4_kobenhavn
            data: {}
      - conditions:
          - condition: trigger
            id: morning-end
        sequence:
          - service: media_player.media_stop
            target:
              entity_id: media_player.living_room
            data: {}
    default: []
mode: single
