alias: Notify when backup stale
description: ''
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.backups_stale
    from: 'on'
condition: []
action:
  - service: notify.mobile_app_oneplus_a5010
    data:
      title: Backups are stale
      message: Backups are failing. Please fix
