blueprint:
  name: Ikea Shortcut button automation
  description: Toggle a device when pressing the button
  domain: automation
  input:
    button:
      name: Shortcut button
      description: This button will toggle the device when pressing it
      selector:
        entity:
          domain: sensor
    target_light:
      name: Lights
      description: The lights to toggle when pressing the button
      selector:
        target:
          entity:
            domain: light
trigger:
  - platform: device
    domain: mqtt
    device_id: !input button
    type: action
    subtype: 'on'
condition: []
action:
  - type: toggle
    entity_id: !input target_light
    domain: light
mode: single
