---
resource_template: https://api.energidataservice.dk/dataset/Elspotprices
scan_interval: 01:00 # 1 hour
params:
  filter: '{"PriceArea":"DK2"}'
  start: |
    {% if states("input_boolean.energy_price_include_yesterday") | default(false) | bool(false) %}
      {{ (now() - timedelta(days = 1)).timestamp() | timestamp_custom('%Y-%m-%d') }}
    {% else %}
      {{ now().timestamp() | timestamp_custom('%Y-%m-%d') }}
    {% endif %}
  limit: 100
  offset: 0
  sort: "HourDK ASC"
  timezone: dk
sensor:
  - name: energy_price_raw
    value_template: "OK"
    json_attributes:
      - records
