---
id: workshop_control_unit_off
alias: Turn off Workshop Control Unit once Timer runs out
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.workshop_switch
  - platform: state
    entity_id: switch.control_unit_1
    to: "off"
action:
  - service: timer.cancel
    data:
      entity_id: timer.workshop_switch
  - service: switch.turn_off
    entity_id: switch.control_unit_1
