---
id: workshop_control_unit_on
alias: Turn on Workshop Control Unit for 3 hours
trigger:
  platform: state
  entity_id: switch.control_unit_1
  to: "on"
action:
  service: timer.start
  entity_id: timer.workshop_switch
