---
id: workshop_toggle_light_strip
alias: Workshop lightstrip toggle
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.workshop_sensor_occupancy
    id: turn-on
    to: 'on'
  - platform: state
    entity_id: binary_sensor.workshop_sensor_occupancy
    id: turn-off
    to: 'off'
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: turn-on
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.workshop_strip
      - conditions:
          - condition: trigger
            id: turn-off
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.workshop_strip
    default: []
mode: single
