---
id: toggle_alarm_using_home_away_button
alias: Toggle Alarm using Home/Away Button
description: ''
mode: single
trigger:
  - platform: state
    entity_id: input_boolean.house_mode_away
    to: 'on'
    id: away
  - platform: state
    entity_id: input_boolean.house_mode_away
    to: 'off'
    id: home
condition: []
action:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id: home
              - condition: not
                conditions:
                  - condition: state
                    entity_id: alarm_control_panel.verisure_alarm
                    state: disarmed
        sequence:
          - service: alarm_control_panel.alarm_arm_home
            data: {}
            target:
              entity_id: alarm_control_panel.verisure_alarm
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id: away
              - condition: not
                conditions:
                  - condition: state
                    entity_id: alarm_control_panel.verisure_alarm
                    state: armed_away
        sequence:
          - service: alarm_control_panel.alarm_arm_away
            data: {}
            target:
              entity_id: alarm_control_panel.verisure_alarm
    default: []
