---
id: wait_for_mobile_response
alias: Wait for mobile response
description: ''
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: WORK_REMOTELY_YES
    id: work-remotely-yes
  - platform: event
    event_type: mobile_app_notification_action
    id: work-remotely-no
    event_data:
      action: WORK_REMOTELY_NO
condition:
  - condition: state
    entity_id: input_boolean.vacation
    state: 'off'
action:
  - choose:
      - conditions:
          - condition: trigger
            id: work-remotely-yes
        sequence:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.work_from_home_today
      - conditions:
          - condition: trigger
            id: work-remotely-no
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id: input_boolean.work_from_home_today
    default: []
mode: single
