alias: Notification Trash being collected
id: waste_collection
description: 'Sends a notification to Kristian on the day that waste is being collected'
trigger:
  - platform: state
    entity_id: sensor.renoweb_140_l_papir_karton
    id: paper-collected
    from: '1'
    to: '0'
  - platform: state
    entity_id: sensor.renoweb_240_l_glas_metal
    id: glass-collected
    from: '1'
    to: '0'
  - platform: state
    entity_id: sensor.renoweb_240_l_rest_mad_14_dag
    id: general-collected
    from: '1'
    to: '0'
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: paper-collected
        sequence:
          - service: notify.mobile_app_ klgn_phone
            data:
              title: Waste is collected today
              message: Paper waste is being collected today
      - conditions:
          - condition: trigger
            id: glass-collected
        sequence:
          - service: notify.mobile_app_klgn_phone
            data:
              title: Waste is collected today
              message: Glass and metal waste is being collected today
      - conditions:
          - condition: trigger
            id: general-collected
        sequence:
          - service: notify.mobile_app_klgn_phone
            data:
              title: Waste is collected today
              message: General waste is being collected today
    default: []
mode: single
